flowchart LR

subgraph 0["src"]
1["App.tsx"]
subgraph 2["components"]
3["SoekBatch.tsx"]
11["JsonModal.tsx"]
12["Tidslinjer.tsx"]
15["AlertWithCloseButton.tsx"]
16["Errorhandler.tsx"]
1D["LabelText.tsx"]
1F["BestilleSkattekortButton.tsx"]
1G["ShowAuditLogg.tsx"]
1H["Skattekortdata.tsx"]
1I["Soek.tsx"]
1K["SoekFlere.tsx"]
end
subgraph 4["types"]
5["Bestillingsbatch.ts"]
S["Audit.ts"]
T["Error.ts"]
U["HentSkattekortRequestSchema.ts"]
V["SkattekortResponseDTOSchema.ts"]
W["SkattekortStatusResponse.ts"]
X["WrappedResponseWithErrorSchema.ts"]
19["Bestilling.ts"]
1A["SokParameter.ts"]
1B["Noekkelinformasjon.ts"]
1C["Utsending.ts"]
1L["FlereFnrRequest.ts"]
2D["UtsendingRequest.ts"]
subgraph 2E["schema"]
2F["EmployeeSchema.ts"]
end
end
subgraph C["util"]
D["dateUtils.ts"]
13["listUtils.ts"]
1M["grafanaFaro.ts"]
1N["environment.ts"]
end
subgraph E["pages"]
F["Batchdetaljer.tsx"]
14["BestillMedFil.tsx"]
17["Frontside.tsx"]
1E["Person.tsx"]
1J["Personer.tsx"]
end
subgraph G["api"]
H["apiService.ts"]
Y["apiConfig.ts"]
subgraph Z["models"]
10["ForespoerselRequest.ts"]
end
18["fetchFrontsideInfo.ts"]
end
1O["main.tsx"]
1P["index.css"]
2G["vite-env.d.ts"]
end
subgraph 6["node_modules"]
subgraph 7[".pnpm"]
subgraph 8["zod@4.4.3"]
subgraph 9["node_modules"]
subgraph A["zod"]
B["index.d.cts"]
end
end
end
subgraph I["axios@1.16.0"]
subgraph J["node_modules"]
subgraph K["axios"]
L["index.d.cts"]
end
end
end
subgraph M["swr@2.4.1_react@19.2.5"]
subgraph N["node_modules"]
subgraph O["swr"]
subgraph P["dist"]
subgraph Q["index"]
R["index.d.mts"]
end
end
end
end
end
subgraph 1Q["react-dom@19.2.5_react@19.2.5"]
subgraph 1R["node_modules"]
subgraph 1S["react-dom"]
1T["client.js"]
end
end
end
subgraph 1W["msw@2.14.3_@types+node@25.6.0_typescript@6.0.3"]
subgraph 1X["node_modules"]
subgraph 1Y["msw"]
subgraph 1Z["lib"]
subgraph 20["browser"]
21["index.d.mts"]
end
subgraph 2B["core"]
2C["index.d.mts"]
end
end
end
end
end
subgraph 2H["vite@8.0.10_@types+node@25.6.0_yaml@2.8.4"]
subgraph 2I["node_modules"]
subgraph 2J["vite"]
2K["client.d.ts"]
end
end
end
end
end
subgraph 1U["mock"]
1V["browser.ts"]
22["handlers.ts"]
23["auditLogg.json"]
24["batcher_mindre.json"]
25["batcherUtenJson.json"]
26["bestillinger.json"]
27["noekkelinformasjon.json"]
28["responseMedMangeSkattekort.json"]
29["responseUtenSkattekort.json"]
2A["utsendinger.json"]
end
1-->3
1-->F
1-->14
1-->17
1-->1E
1-->1J
1-->1M
3-->5
3-->D
5-->B
F-->H
F-->11
F-->3
F-->12
F-->5
F-->D
H-->S
H-->5
H-->T
H-->U
H-->V
H-->W
H-->X
H-->Y
H-->10
H-->L
H-->R
H-->B
S-->B
U-->B
V-->B
W-->B
X-->S
X-->V
X-->B
Y-->T
Y-->L
10-->B
12-->5
12-->D
12-->13
13-->S
13-->5
13-->V
14-->H
14-->15
14-->16
14-->T
16-->H
16-->T
17-->H
17-->18
17-->15
17-->1D
17-->D
18-->19
18-->5
18-->1B
18-->1C
18-->Y
18-->H
18-->L
18-->R
19-->5
19-->1A
19-->B
1A-->B
1B-->B
1C-->1A
1C-->B
1E-->H
1E-->15
1E-->1F
1E-->16
1E-->1D
1E-->1G
1E-->1I
1F-->H
1F-->10
1G-->H
1G-->S
1G-->V
1G-->D
1G-->13
1G-->16
1G-->1H
1H-->V
1H-->D
1H-->1D
1I-->1A
1J-->15
1J-->1K
1K-->1L
1L-->B
1M-->1N
1O-->1V
1O-->1
1O-->1P
1O-->1T
1V-->22
1V-->21
22-->U
22-->D
22-->23
22-->24
22-->25
22-->26
22-->27
22-->28
22-->29
22-->2A
22-->2C
2D-->B
2F-->B
2G-->2K
