apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skattekort-admin
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://sokos-skattekort-admin.intern.dev.nav.no"
    - "https://sokos-skattekort-admin.ansatt.dev.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "b9c50759-8b85-4502-bfee-530d1cdb49ba" # skatt-og-trekk-ops
          - id: "f760594e-4918-4246-a636-329148c82fa7" 
          - id: "0970c9f3-d599-4996-862c-012b61541be3"
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-skattekort.intern.dev.nav.no
      rules:
        - application: sokos-skattekort
          namespace: okonomi