apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-skattekort-admin
  namespace: okonomi
  labels:
    team: okonomi
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 2
    max: 2
  ingresses:
    - "https://sokos-skattekort-admin.intern.nav.no"
    - "https://sokos-skattekort-admin.ansatt.nav.no"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "0918ffcf-2cc4-4282-a1d0-757e116a1d9f" # skatt-og-trekk
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/*
  accessPolicy:
    outbound:
      external:
        - host: sokos-skattekort.intern.nav.no
      rules:
        - application: sokos-skattekort
          namespace: okonomi