apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skattekort-admin
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /admin/internal/isAlive
    initialDelay: 10
  readiness:
    path: /admin/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /admin/internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://sokos-skattekort.intern.dev.nav.no/admin"
    - "https://sokos-skattekort.ansatt.dev.nav.no/admin"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
